<?php

namespace Database\Seeders;

use App\Models\Stage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StagesSeeder extends Seeder
{
    public function run(): void
    {
        $stages = [
            [
                'rally_id' => 1,
                'name' => 'Rambla del Cañar',
                'surface' => 'Grava',
                'length_km' => 15.2,
                'start_point_lat' => 37.7921,
                'start_point_lng' => -1.7773,
                'end_point_lat' => 37.7768,
                'end_point_lng' => -1.7490,
                'route' => json_encode([
                    ['lat' => 37.7905, 'lng' => -1.7740],
                    ['lat' => 37.7850, 'lng' => -1.7690],
                    ['lat' => 37.7810, 'lng' => -1.7625],
                    ['lat' => 37.7785, 'lng' => -1.7565],
                    ['lat' => 37.7778, 'lng' => -1.7520],
                ]),
            ],
            [
                'rally_id' => 1,
                'name' => 'La Tova - Zarzilla',
                'surface' => 'Grava',
                'length_km' => 17.4,
                'start_point_lat' => 37.8120,
                'start_point_lng' => -1.9250,
                'end_point_lat' => 37.8402,
                'end_point_lng' => -1.8958,
                'route' => json_encode([
                    ['lat' => 37.8160, 'lng' => -1.9205],
                    ['lat' => 37.8210, 'lng' => -1.9120],
                    ['lat' => 37.8275, 'lng' => -1.9055],
                    ['lat' => 37.8330, 'lng' => -1.9000],
                    ['lat' => 37.8375, 'lng' => -1.8970],
                ]),
            ],
            [
                'rally_id' => 1,
                'name' => 'Campo López',
                'surface' => 'Grava',
                'length_km' => 13.6,
                'start_point_lat' => 37.6710,
                'start_point_lng' => -1.7922,
                'end_point_lat' => 37.6920,
                'end_point_lng' => -1.7561,
                'route' => json_encode([
                    ['lat' => 37.6745, 'lng' => -1.7850],
                    ['lat' => 37.6780, 'lng' => -1.7760],
                    ['lat' => 37.6830, 'lng' => -1.7675],
                    ['lat' => 37.6885, 'lng' => -1.7600],
                ]),
            ],
            [
                'rally_id' => 2,
                'name' => 'Las Ermitas - Trassierra',
                'surface' => 'Asfalto',
                'length_km' => 16.8,
                'start_point_lat' => 37.8840,
                'start_point_lng' => -4.8190,
                'end_point_lat' => 37.8975,
                'end_point_lng' => -4.8825,
                'route' => json_encode([
                    ['lat' => 37.8855, 'lng' => -4.8240],
                    ['lat' => 37.8880, 'lng' => -4.8325],
                    ['lat' => 37.8905, 'lng' => -4.8430],
                    ['lat' => 37.8932, 'lng' => -4.8550],
                    ['lat' => 37.8950, 'lng' => -4.8705],
                ]),
            ],
            [
                'rally_id' => 2,
                'name' => 'El Brillante - Cerro Muriano',
                'surface' => 'Mixto',
                'length_km' => 14.3,
                'start_point_lat' => 37.9042,
                'start_point_lng' => -4.7941,
                'end_point_lat' => 37.9481,
                'end_point_lng' => -4.8147,
                'route' => json_encode([
                    ['lat' => 37.9080, 'lng' => -4.7985],
                    ['lat' => 37.9202, 'lng' => -4.8043],
                    ['lat' => 37.9301, 'lng' => -4.8099],
                    ['lat' => 37.9400, 'lng' => -4.8120],
                ]),
            ],
            [
                'rally_id' => 2,
                'name' => 'Villaviciosa - Trasierra',
                'surface' => 'Grava',
                'length_km' => 20.1,
                'start_point_lat' => 37.9540,
                'start_point_lng' => -5.0300,
                'end_point_lat' => 37.9044,
                'end_point_lng' => -4.9202,
                'route' => json_encode([
                    ['lat' => 37.9480, 'lng' => -5.0150],
                    ['lat' => 37.9335, 'lng' => -4.9900],
                    ['lat' => 37.9250, 'lng' => -4.9600],
                    ['lat' => 37.9120, 'lng' => -4.9350],
                ]),
            ],
            [
                'rally_id' => 3,
                'name' => 'A Peroxa - Luintra',
                'surface' => 'Asfalto',
                'length_km' => 17.6,
                'start_point_lat' => 42.4444,
                'start_point_lng' => -7.7562,
                'end_point_lat' => 42.4312,
                'end_point_lng' => -7.6791,
                'route' => json_encode([
                    ['lat' => 42.4430, 'lng' => -7.7480],
                    ['lat' => 42.4400, 'lng' => -7.7350],
                    ['lat' => 42.4375, 'lng' => -7.7200],
                    ['lat' => 42.4350, 'lng' => -7.7000],
                ]),
            ],
            [
                'rally_id' => 3,
                'name' => 'San Pedro de Rocas - Esgos',
                'surface' => 'Grava',
                'length_km' => 12.9,
                'start_point_lat' => 42.3955,
                'start_point_lng' => -7.6550,
                'end_point_lat' => 42.4125,
                'end_point_lng' => -7.6102,
                'route' => json_encode([
                    ['lat' => 42.3980, 'lng' => -7.6480],
                    ['lat' => 42.4030, 'lng' => -7.6350],
                    ['lat' => 42.4075, 'lng' => -7.6220],
                ]),
            ],
            [
                'rally_id' => 3,
                'name' => 'Castro Caldelas - Parada de Sil',
                'surface' => 'Mixto',
                'length_km' => 19.3,
                'start_point_lat' => 42.3701,
                'start_point_lng' => -7.4160,
                'end_point_lat' => 42.3777,
                'end_point_lng' => -7.5488,
                'route' => json_encode([
                    ['lat' => 42.3720, 'lng' => -7.4300],
                    ['lat' => 42.3755, 'lng' => -7.4600],
                    ['lat' => 42.3765, 'lng' => -7.4900],
                    ['lat' => 42.3772, 'lng' => -7.5200],
                ]),
            ],
            [
                'rally_id' => 4,
                'name' => 'Oia - Mougás',
                'surface' => 'Mixto',
                'length_km' => 14.8,
                'start_point_lat' => 42.0600,
                'start_point_lng' => -8.8970,
                'end_point_lat' => 42.1385,
                'end_point_lng' => -8.8662,
                'route' => json_encode([
                    ['lat' => 42.0700, 'lng' => -8.8900],
                    ['lat' => 42.0900, 'lng' => -8.8800],
                    ['lat' => 42.1150, 'lng' => -8.8720],
                ]),
            ],
            [
                'rally_id' => 4,
                'name' => 'Baiona - Baredo',
                'surface' => 'Asfalto',
                'length_km' => 11.2,
                'start_point_lat' => 42.1168,
                'start_point_lng' => -8.8474,
                'end_point_lat' => 42.1244,
                'end_point_lng' => -8.8400,
                'route' => json_encode([
                    ['lat' => 42.1180, 'lng' => -8.8450],
                    ['lat' => 42.1210, 'lng' => -8.8420],
                ]),
            ],
            [
                'rally_id' => 4,
                'name' => 'Tomiño - Tebra',
                'surface' => 'Grava',
                'length_km' => 17.0,
                'start_point_lat' => 42.0520,
                'start_point_lng' => -8.7280,
                'end_point_lat' => 42.0940,
                'end_point_lng' => -8.7172,
                'route' => json_encode([
                    ['lat' => 42.0600, 'lng' => -8.7250],
                    ['lat' => 42.0700, 'lng' => -8.7220],
                    ['lat' => 42.0800, 'lng' => -8.7200],
                ]),
            ],
            [
                'rally_id' => 5,
                'name' => 'La Manjoya - El Escamplero',
                'surface' => 'Asfalto',
                'length_km' => 12.5,
                'start_point_lat' => 43.3501,
                'start_point_lng' => -5.8503,
                'end_point_lat' => 43.3744,
                'end_point_lng' => -5.9166,
                'route' => json_encode([
                    ['lat' => 43.3550, 'lng' => -5.8600],
                    ['lat' => 43.3600, 'lng' => -5.8800],
                    ['lat' => 43.3680, 'lng' => -5.9000],
                ]),
            ],
            [
                'rally_id' => 5,
                'name' => 'Trubia - Sograndio',
                'surface' => 'Mixto',
                'length_km' => 15.9,
                'start_point_lat' => 43.3520,
                'start_point_lng' => -6.0090,
                'end_point_lat' => 43.3842,
                'end_point_lng' => -5.9731,
                'route' => json_encode([
                    ['lat' => 43.3580, 'lng' => -6.0000],
                    ['lat' => 43.3660, 'lng' => -5.9900],
                    ['lat' => 43.3740, 'lng' => -5.9800],
                ]),
            ],
            [
                'rally_id' => 5,
                'name' => 'Las Caldas - Latores',
                'surface' => 'Asfalto',
                'length_km' => 10.6,
                'start_point_lat' => 43.3371,
                'start_point_lng' => -5.9180,
                'end_point_lat' => 43.3539,
                'end_point_lng' => -5.8630,
                'route' => json_encode([
                    ['lat' => 43.3400, 'lng' => -5.9050],
                    ['lat' => 43.3450, 'lng' => -5.8900],
                    ['lat' => 43.3500, 'lng' => -5.8750],
                ]),
            ],
            [
                'rally_id' => 6,
                'name' => 'Nueva - Pría',
                'surface' => 'Mixto',
                'length_km' => 13.7,
                'start_point_lat' => 43.4286,
                'start_point_lng' => -4.9832,
                'end_point_lat' => 43.4281,
                'end_point_lng' => -4.9234,
                'route' => json_encode([
                    ['lat' => 43.4290, 'lng' => -4.9750],
                    ['lat' => 43.4295, 'lng' => -4.9600],
                    ['lat' => 43.4289, 'lng' => -4.9440],
                ]),
            ],
            [
                'rally_id' => 6,
                'name' => 'El Mazucu - Rales',
                'surface' => 'Asfalto',
                'length_km' => 16.1,
                'start_point_lat' => 43.3715,
                'start_point_lng' => -4.8843,
                'end_point_lat' => 43.3952,
                'end_point_lng' => -4.9440,
                'route' => json_encode([
                    ['lat' => 43.3740, 'lng' => -4.8950],
                    ['lat' => 43.3820, 'lng' => -4.9100],
                    ['lat' => 43.3900, 'lng' => -4.9300],
                ]),
            ],
            [
                'rally_id' => 6,
                'name' => 'Posada - Parres',
                'surface' => 'Grava',
                'length_km' => 11.3,
                'start_point_lat' => 43.4002,
                'start_point_lng' => -4.7884,
                'end_point_lat' => 43.4193,
                'end_point_lng' => -4.8212,
                'route' => json_encode([
                    ['lat' => 43.4040, 'lng' => -4.7950],
                    ['lat' => 43.4080, 'lng' => -4.8050],
                    ['lat' => 43.4140, 'lng' => -4.8140],
                ]),
            ],
            [
                'rally_id' => 7,
                'name' => 'Mont-Roig - Colldejou',
                'surface' => 'Asfalto',
                'length_km' => 14.2,
                'start_point_lat' => 41.0400,
                'start_point_lng' => 0.9780,
                'end_point_lat' => 41.0800,
                'end_point_lng' => 0.9120,
                'route' => json_encode([
                    ['lat' => 41.0450, 'lng' => 0.9680],
                    ['lat' => 41.0600, 'lng' => 0.9500],
                    ['lat' => 41.0700, 'lng' => 0.9300],
                ]),
            ],
            [
                'rally_id' => 7,
                'name' => 'Riudecanyes - Duesaigües',
                'surface' => 'Mixto',
                'length_km' => 16.9,
                'start_point_lat' => 41.1200,
                'start_point_lng' => 0.9820,
                'end_point_lat' => 41.1400,
                'end_point_lng' => 0.9260,
                'route' => json_encode([
                    ['lat' => 41.1250, 'lng' => 0.9650],
                    ['lat' => 41.1300, 'lng' => 0.9450],
                    ['lat' => 41.1360, 'lng' => 0.9300],
                ]),
            ],
            [
                'rally_id' => 7,
                'name' => 'La Mussara - Vilaplana',
                'surface' => 'Grava',
                'length_km' => 12.7,
                'start_point_lat' => 41.2600,
                'start_point_lng' => 1.0000,
                'end_point_lat' => 41.2800,
                'end_point_lng' => 0.9600,
                'route' => json_encode([
                    ['lat' => 41.2650, 'lng' => 0.9900],
                    ['lat' => 41.2700, 'lng' => 0.9750],
                    ['lat' => 41.2750, 'lng' => 0.9650],
                ]),
            ],
        
            // Rallye de La Nucía - Trofeo Costa Blanca
            [
                'rally_id' => 8,
                'name' => 'Guadalest - Benifato',
                'surface' => 'Asfalto',
                'length_km' => 10.6,
                'start_point_lat' => 38.6760,
                'start_point_lng' => -0.2020,
                'end_point_lat' => 38.7000,
                'end_point_lng' => -0.1770,
                'route' => json_encode([
                    ['lat' => 38.6820, 'lng' => -0.1950],
                    ['lat' => 38.6900, 'lng' => -0.1850],
                    ['lat' => 38.6950, 'lng' => -0.1800],
                ]),
            ],
            [
                'rally_id' => 8,
                'name' => 'Callosa - Tárbena',
                'surface' => 'Mixto',
                'length_km' => 14.1,
                'start_point_lat' => 38.6480,
                'start_point_lng' => -0.1090,
                'end_point_lat' => 38.6730,
                'end_point_lng' => -0.0800,
                'route' => json_encode([
                    ['lat' => 38.6550, 'lng' => -0.1000],
                    ['lat' => 38.6620, 'lng' => -0.0900],
                    ['lat' => 38.6680, 'lng' => -0.0850],
                ]),
            ],
            [
                'rally_id' => 8,
                'name' => 'Bolulla - Castell de Castells',
                'surface' => 'Grava',
                'length_km' => 17.3,
                'start_point_lat' => 38.6880,
                'start_point_lng' => -0.1500,
                'end_point_lat' => 38.7100,
                'end_point_lng' => -0.1100,
                'route' => json_encode([
                    ['lat' => 38.6950, 'lng' => -0.1400],
                    ['lat' => 38.7000, 'lng' => -0.1300],
                    ['lat' => 38.7050, 'lng' => -0.1200],
                ]),
            ],
            [
                'rally_id' => 9,
                'name' => 'Tramo A',
                'start_point_lat' => 42.2321,
                'start_point_lng' => -8.7323,
                'end_point_lat' => 42.2510,
                'end_point_lng' => -8.7010,
                'length_km' => 14.50,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 42.2389, 'lng' => -8.7156],
                    ['lat' => 42.2445, 'lng' => -8.7103],
                    ['lat' => 42.2495, 'lng' => -8.7032],
                ]),
            ],
            [
                'rally_id' => 9,
                'name' => 'Tramo B',
                'start_point_lat' => 42.2600,
                'start_point_lng' => -8.7105,
                'end_point_lat' => 42.2801,
                'end_point_lng' => -8.6800,
                'length_km' => 18.00,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 42.2645, 'lng' => -8.7050],
                    ['lat' => 42.2700, 'lng' => -8.6950],
                    ['lat' => 42.2750, 'lng' => -8.6850],
                ]),
            ],
            [
                'rally_id' => 9,
                'name' => 'Tramo C',
                'start_point_lat' => 42.2733,
                'start_point_lng' => -8.7325,
                'end_point_lat' => 42.2900,
                'end_point_lng' => -8.7101,
                'length_km' => 16.20,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 42.2760, 'lng' => -8.7230],
                    ['lat' => 42.2800, 'lng' => -8.7150],
                    ['lat' => 42.2850, 'lng' => -8.7100],
                    ['lat' => 42.2900, 'lng' => -8.7101],
                ]),
            ],
            [
                'rally_id' => 10,
                'name' => 'Tramo A',
                'start_point_lat' => 43.3603,
                'start_point_lng' => -5.8442,
                'end_point_lat' => 43.3755,
                'end_point_lng' => -5.8267,
                'length_km' => 14.00,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 43.3650, 'lng' => -5.8380],
                    ['lat' => 43.3700, 'lng' => -5.8300],
                    ['lat' => 43.3755, 'lng' => -5.8267],
                ]),
            ],
            [
                'rally_id' => 10,
                'name' => 'Tramo B',
                'start_point_lat' => 43.3777,
                'start_point_lng' => -5.8320,
                'end_point_lat' => 43.3970,
                'end_point_lng' => -5.8105,
                'length_km' => 15.50,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 43.3800, 'lng' => -5.8250],
                    ['lat' => 43.3870, 'lng' => -5.8170],
                    ['lat' => 43.3920, 'lng' => -5.8125],
                ]),
            ],
            [
                'rally_id' => 10,
                'name' => 'Tramo C',
                'start_point_lat' => 43.3800,
                'start_point_lng' => -5.8110,
                'end_point_lat' => 43.4000,
                'end_point_lng' => -5.7900,
                'length_km' => 17.80,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 43.3833, 'lng' => -5.8033],
                    ['lat' => 43.3900, 'lng' => -5.7950],
                    ['lat' => 43.3950, 'lng' => -5.7925],
                    ['lat' => 43.4000, 'lng' => -5.7900],
                ]),
            ],
            [
                'rally_id' => 11,
                'name' => 'Tramo A',
                'start_point_lat' => 43.4115,
                'start_point_lng' => -4.7560,
                'end_point_lat' => 43.4300,
                'end_point_lng' => -4.7333,
                'length_km' => 12.80,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 43.4150, 'lng' => -4.7450],
                    ['lat' => 43.4200, 'lng' => -4.7380],
                    ['lat' => 43.4300, 'lng' => -4.7333],
                ]),
            ],
            [
                'rally_id' => 11,
                'name' => 'Tramo B',
                'start_point_lat' => 43.4385,
                'start_point_lng' => -4.7320,
                'end_point_lat' => 43.4512,
                'end_point_lng' => -4.7123,
                'length_km' => 14.00,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 43.4400, 'lng' => -4.7250],
                    ['lat' => 43.4450, 'lng' => -4.7180],
                    ['lat' => 43.4512, 'lng' => -4.7123],
                ]),
            ],
            [
                'rally_id' => 11,
                'name' => 'Tramo C',
                'start_point_lat' => 43.4500,
                'start_point_lng' => -4.7155,
                'end_point_lat' => 43.4670,
                'end_point_lng' => -4.6980,
                'length_km' => 16.40,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 43.4520, 'lng' => -4.7080],
                    ['lat' => 43.4600, 'lng' => -4.7025],
                    ['lat' => 43.4670, 'lng' => -4.6980],
                ]),
            ],
            [
                'rally_id' => 12,
                'name' => 'Tramo A',
                'start_point_lat' => 41.1085,
                'start_point_lng' => 1.1483,
                'end_point_lat' => 41.1300,
                'end_point_lng' => 1.1450,
                'length_km' => 11.50,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 41.1150, 'lng' => 1.1470],
                    ['lat' => 41.1200, 'lng' => 1.1460],
                    ['lat' => 41.1300, 'lng' => 1.1450],
                ]),
            ],
            [
                'rally_id' => 12,
                'name' => 'Tramo B',
                'start_point_lat' => 41.1400,
                'start_point_lng' => 1.1400,
                'end_point_lat' => 41.1600,
                'end_point_lng' => 1.1300,
                'length_km' => 15.30,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 41.1450, 'lng' => 1.1350],
                    ['lat' => 41.1500, 'lng' => 1.1320],
                    ['lat' => 41.1600, 'lng' => 1.1300],
                ]),
            ],
            [
                'rally_id' => 12,
                'name' => 'Tramo C',
                'start_point_lat' => 41.1580,
                'start_point_lng' => 1.1280,
                'end_point_lat' => 41.1800,
                'end_point_lng' => 1.1200,
                'length_km' => 18.40,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 41.1650, 'lng' => 1.1250],
                    ['lat' => 41.1720, 'lng' => 1.1230],
                    ['lat' => 41.1800, 'lng' => 1.1200],
                ]),
            ],
            [
                'rally_id' => 13,
                'name' => 'Tramo A',
                'start_point_lat' => 40.0738,
                'start_point_lng' => -2.1372,
                'end_point_lat' => 40.0850,
                'end_point_lng' => -2.1155,
                'length_km' => 13.60,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 40.0780, 'lng' => -2.1250],
                    ['lat' => 40.0800, 'lng' => -2.1180],
                    ['lat' => 40.0850, 'lng' => -2.1155],
                ]),
            ],
            [
                'rally_id' => 13,
                'name' => 'Tramo B',
                'start_point_lat' => 40.0800,
                'start_point_lng' => -2.1100,
                'end_point_lat' => 40.1000,
                'end_point_lng' => -2.0900,
                'length_km' => 15.00,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 40.0850, 'lng' => -2.1000],
                    ['lat' => 40.0900, 'lng' => -2.0950],
                    ['lat' => 40.1000, 'lng' => -2.0900],
                ]),
            ],
            [
                'rally_id' => 13,
                'name' => 'Tramo C',
                'start_point_lat' => 40.1000,
                'start_point_lng' => -2.0900,
                'end_point_lat' => 40.1200,
                'end_point_lng' => -2.0800,
                'length_km' => 18.30,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 40.1050, 'lng' => -2.0850],
                    ['lat' => 40.1100, 'lng' => -2.0800],
                    ['lat' => 40.1200, 'lng' => -2.0800],
                ]),
            ],
            [
                'rally_id' => 14,
                'name' => 'Tramo A',
                'start_point_lat' => 42.6000,
                'start_point_lng' => -5.5700,
                'end_point_lat' => 42.6100,
                'end_point_lng' => -5.5600,
                'length_km' => 14.00,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 42.6050, 'lng' => -5.5650],
                    ['lat' => 42.6100, 'lng' => -5.5600],
                ]),
            ],
            [
                'rally_id' => 14,
                'name' => 'Tramo B',
                'start_point_lat' => 42.6150,
                'start_point_lng' => -5.5500,
                'end_point_lat' => 42.6250,
                'end_point_lng' => -5.5400,
                'length_km' => 16.80,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 42.6200, 'lng' => -5.5450],
                    ['lat' => 42.6250, 'lng' => -5.5400],
                ]),
            ],
            [
                'rally_id' => 14,
                'name' => 'Tramo C',
                'start_point_lat' => 42.6250,
                'start_point_lng' => -5.5400,
                'end_point_lat' => 42.6350,
                'end_point_lng' => -5.5300,
                'length_km' => 18.30,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 42.6300, 'lng' => -5.5350],
                    ['lat' => 42.6350, 'lng' => -5.5300],
                ]),
            ],
            [
                'rally_id' => 15,
                'name' => 'Tramo A',
                'start_point_lat' => 29.0500,
                'start_point_lng' => -13.5000,
                'end_point_lat' => 29.0600,
                'end_point_lng' => -13.4900,
                'length_km' => 12.90,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 29.0550, 'lng' => -13.4950],
                    ['lat' => 29.0600, 'lng' => -13.4900],
                ]),
            ],
            [
                'rally_id' => 15,
                'name' => 'Tramo B',
                'start_point_lat' => 29.0650,
                'start_point_lng' => -13.4800,
                'end_point_lat' => 29.0750,
                'end_point_lng' => -13.4700,
                'length_km' => 15.30,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 29.0700, 'lng' => -13.4750],
                    ['lat' => 29.0750, 'lng' => -13.4700],
                ]),
            ],
            [
                'rally_id' => 15,
                'name' => 'Tramo C',
                'start_point_lat' => 29.0750,
                'start_point_lng' => -13.4700,
                'end_point_lat' => 29.0850,
                'end_point_lng' => -13.4600,
                'length_km' => 16.00,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 29.0800, 'lng' => -13.4650],
                    ['lat' => 29.0850, 'lng' => -13.4600],
                ]),
            ],
            [
                'rally_id' => 16,
                'name' => 'Tramo A',
                'start_point_lat' => 37.1700,
                'start_point_lng' => -3.5900,
                'end_point_lat' => 37.1800,
                'end_point_lng' => -3.5800,
                'length_km' => 14.50,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 37.1750, 'lng' => -3.5850],
                    ['lat' => 37.1800, 'lng' => -3.5800],
                ]),
            ],
            [
                'rally_id' => 16,
                'name' => 'Tramo B',
                'start_point_lat' => 37.1850,
                'start_point_lng' => -3.5700,
                'end_point_lat' => 37.1950,
                'end_point_lng' => -3.5600,
                'length_km' => 13.20,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 37.1900, 'lng' => -3.5650],
                    ['lat' => 37.1950, 'lng' => -3.5600],
                ]),
            ],
            [
                'rally_id' => 16,
                'name' => 'Tramo C',
                'start_point_lat' => 37.1950,
                'start_point_lng' => -3.5600,
                'end_point_lat' => 37.2050,
                'end_point_lng' => -3.5500,
                'length_km' => 16.00,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 37.2000, 'lng' => -3.5550],
                    ['lat' => 37.2050, 'lng' => -3.5500],
                ]),
            ],
            [
                'rally_id' => 17,
                'name' => 'Tramo A',
                'start_point_lat' => 40.6000,
                'start_point_lng' => -3.1600,
                'end_point_lat' => 40.6100,
                'end_point_lng' => -3.1500,
                'length_km' => 10.80,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 40.6050, 'lng' => -3.1550],
                    ['lat' => 40.6100, 'lng' => -3.1500],
                ]),
            ],
            [
                'rally_id' => 17,
                'name' => 'Tramo B',
                'start_point_lat' => 40.6150,
                'start_point_lng' => -3.1400,
                'end_point_lat' => 40.6250,
                'end_point_lng' => -3.1300,
                'length_km' => 12.10,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 40.6200, 'lng' => -3.1350],
                    ['lat' => 40.6250, 'lng' => -3.1300],
                ]),
            ],
            [
                'rally_id' => 17,
                'name' => 'Tramo C',
                'start_point_lat' => 40.6250,
                'start_point_lng' => -3.1300,
                'end_point_lat' => 40.6350,
                'end_point_lng' => -3.1200,
                'length_km' => 14.50,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 40.6300, 'lng' => -3.1250],
                    ['lat' => 40.6350, 'lng' => -3.1200],
                ]),
            ],
            [
                'rally_id' => 18,
                'name' => 'Tramo A',
                'start_point_lat' => 38.8800,
                'start_point_lng' => -6.9500,
                'end_point_lat' => 38.8900,
                'end_point_lng' => -6.9400,
                'length_km' => 18.00,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 38.8850, 'lng' => -6.9450],
                    ['lat' => 38.8900, 'lng' => -6.9400],
                ]),
            ],
            [
                'rally_id' => 18,
                'name' => 'Tramo B',
                'start_point_lat' => 38.8950,
                'start_point_lng' => -6.9300,
                'end_point_lat' => 38.9050,
                'end_point_lng' => -6.9200,
                'length_km' => 20.50,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 38.9000, 'lng' => -6.9250],
                    ['lat' => 38.9050, 'lng' => -6.9200],
                ]),
            ],
            [
                'rally_id' => 18,
                'name' => 'Tramo C',
                'start_point_lat' => 38.9050,
                'start_point_lng' => -6.9200,
                'end_point_lat' => 38.9150,
                'end_point_lng' => -6.9100,
                'length_km' => 22.70,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 38.9100, 'lng' => -6.9150],
                    ['lat' => 38.9150, 'lng' => -6.9100],
                ]),
            ],
            [
                'rally_id' => 19,
                'name' => 'Tramo A',
                'start_point_lat' => 37.6800,
                'start_point_lng' => -1.7000,
                'end_point_lat' => 37.6900,
                'end_point_lng' => -1.6900,
                'length_km' => 15.20,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 37.6850, 'lng' => -1.6950],
                    ['lat' => 37.6900, 'lng' => -1.6900],
                ]),
            ],
            [
                'rally_id' => 19,
                'name' => 'Tramo B',
                'start_point_lat' => 37.6950,
                'start_point_lng' => -1.6800,
                'end_point_lat' => 37.7050,
                'end_point_lng' => -1.6700,
                'length_km' => 17.10,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 37.7000, 'lng' => -1.6750],
                    ['lat' => 37.7050, 'lng' => -1.6700],
                ]),
            ],
            [
                'rally_id' => 19,
                'name' => 'Tramo C',
                'start_point_lat' => 37.7050,
                'start_point_lng' => -1.6700,
                'end_point_lat' => 37.7150,
                'end_point_lng' => -1.6600,
                'length_km' => 19.40,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 37.7100, 'lng' => -1.6650],
                    ['lat' => 37.7150, 'lng' => -1.6600],
                ]),
            ],
            [
                'rally_id' => 20,
                'name' => 'Tramo A',
                'start_point_lat' => 40.2700,
                'start_point_lng' => -0.4700,
                'end_point_lat' => 40.2800,
                'end_point_lng' => -0.4600,
                'length_km' => 22.20,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 40.2750, 'lng' => -0.4650],
                    ['lat' => 40.2800, 'lng' => -0.4600],
                ]),
            ],
            [
                'rally_id' => 20,
                'name' => 'Tramo B',
                'start_point_lat' => 40.2850,
                'start_point_lng' => -0.4500,
                'end_point_lat' => 40.2950,
                'end_point_lng' => -0.4400,
                'length_km' => 24.60,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 40.2900, 'lng' => -0.4450],
                    ['lat' => 40.2950, 'lng' => -0.4400],
                ]),
            ],
            [
                'rally_id' => 20,
                'name' => 'Tramo C',
                'start_point_lat' => 40.2950,
                'start_point_lng' => -0.4400,
                'end_point_lat' => 40.3050,
                'end_point_lng' => -0.4300,
                'length_km' => 26.80,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 40.3000, 'lng' => -0.4350],
                    ['lat' => 40.3050, 'lng' => -0.4300],
                ]),
            ],
            [
                'rally_id' => 21,
                'name' => 'Tramo A',
                'start_point_lat' => 41.6500,
                'start_point_lng' => -0.8800,
                'end_point_lat' => 41.6600,
                'end_point_lng' => -0.8700,
                'length_km' => 13.00,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 41.6550, 'lng' => -0.8750],
                    ['lat' => 41.6600, 'lng' => -0.8700],
                ]),
            ],
            [
                'rally_id' => 21,
                'name' => 'Tramo B',
                'start_point_lat' => 41.6650,
                'start_point_lng' => -0.8600,
                'end_point_lat' => 41.6750,
                'end_point_lng' => -0.8500,
                'length_km' => 14.50,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 41.6700, 'lng' => -0.8550],
                    ['lat' => 41.6750, 'lng' => -0.8500],
                ]),
            ],
            [
                'rally_id' => 21,
                'name' => 'Tramo C',
                'start_point_lat' => 41.6750,
                'start_point_lng' => -0.8500,
                'end_point_lat' => 41.6850,
                'end_point_lng' => -0.8400,
                'length_km' => 16.20,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 41.6800, 'lng' => -0.8450],
                    ['lat' => 41.6850, 'lng' => -0.8400],
                ]),
            ],
            [
                'rally_id' => 22,
                'name' => 'Tramo A',
                'start_point_lat' => 40.0738,
                'start_point_lng' => -2.1372,
                'end_point_lat' => 40.0850,
                'end_point_lng' => -2.1155,
                'length_km' => 13.60,
                'surface' => 'Asfalto',
                'route' => json_encode([
                    ['lat' => 40.0780, 'lng' => -2.1250],
                    ['lat' => 40.0800, 'lng' => -2.1180],
                    ['lat' => 40.0850, 'lng' => -2.1155],
                ]),
            ],
            [
                'rally_id' => 22,
                'name' => 'Tramo B',
                'start_point_lat' => 40.0800,
                'start_point_lng' => -2.1100,
                'end_point_lat' => 40.1000,
                'end_point_lng' => -2.0900,
                'length_km' => 15.00,
                'surface' => 'Grava',
                'route' => json_encode([
                    ['lat' => 40.0850, 'lng' => -2.1000],
                    ['lat' => 40.0900, 'lng' => -2.0950],
                    ['lat' => 40.1000, 'lng' => -2.0900],
                ]),
            ],
            [
                'rally_id' => 22,
                'name' => 'Tramo C',
                'start_point_lat' => 40.1000,
                'start_point_lng' => -2.0900,
                'end_point_lat' => 40.1200,
                'end_point_lng' => -2.0800,
                'length_km' => 18.30,
                'surface' => 'Mixto',
                'route' => json_encode([
                    ['lat' => 40.1050, 'lng' => -2.0850],
                    ['lat' => 40.1100, 'lng' => -2.0800],
                    ['lat' => 40.1200, 'lng' => -2.0800],
                ]),
            ],
        ];



        foreach ($stages as $stage) {
            Stage::create($stage);
        }
    }
}
